blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name  = 'blog'

urlpatterns = [

    path('' , blog_view, name='index'),
    path('<int:pid>', blog_single_view, name='single'),
    path('category/<str:cat_name>' , blog_view, name='category'),
    path('tag/<str:tag_name>' , blog_view, name='tag'),
    path('author/<str:author_username>' , blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('rss/feed/', LatestEntriesFeed()),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from website.views import *
from blog.sitemaps import *

sitemaps = {
    'static': StaticViewSitemap,
    'blog' : BlogSitemap,
}

# from website.views import redirect_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('', include('account.urls')),
    
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^robots\.txt', include('robots.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')), # The CKEditor path
    path('captcha/', include('captcha.urls')),
]

# admin interface Header
admin.site.site_header = 'Mikey'

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#MAINTENANCE_MODE
from django.urls import re_path
from django.conf import settings
from django.views.generic.base import TemplateView

if settings.MAINTENANCE_MODE:
   urlpatterns.insert(0, re_path(r'^', TemplateView.as_view(template_name='maintenance.html'), name='maintenance'))

website/urls.py
from django.urls import path
from website.views import *

app_name  = 'website'

urlpatterns = [

    path('' , index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view , name='contact'),
    path('newsletter', newsletter_view , name='newsletter'),
]

website/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=80)
    email = models.EmailField()
    subject = models.CharField(max_length=100, null=True, blank=True, default=None)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['-created_date']
    def __str__(self):
        return "{} - {}".format(self.name, self.subject)
    
class Newsletter(models.Model):
    email = models.EmailField()
    def __str__(self):
        return self.email

website/forms.py
from django.forms import ModelForm
from website.models import *
from captcha.fields import CaptchaField

class ContactForm(ModelForm):
    captcha = CaptchaField()
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['subject'].required = False
        
    class Meta:
        model = Contact
        fields = '__all__'
        

class NewsletterForm(ModelForm):
    class Meta:
        model = Newsletter
        fields = '__all__'
    
        

website/views.py
from django.shortcuts import render, HttpResponseRedirect
from website.forms import *
from django.contrib import messages
# Create your views here.

def index_view(request):
    return render(request, 'website/index.html')

def about_view(request):
    return render(request, 'website/about.html')

def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            new_contact = form.save(commit=False)
            new_contact.name = 'Unknown'     # warning simple-captcha is enabled.
            new_contact.save()
            messages.add_message(request, messages.SUCCESS, 'Your ticket submited successfully.')
        else:
            messages.add_message(request, messages.ERROR, "Your ticket didn't submit, make sure you have a valid ticket and try again.")
    form = ContactForm()
    return render(request, 'website/contact.html' , context={'form': form})

def newsletter_view(request):
    if request.method == 'POST':
        form = NewsletterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Your email submited successfully.')
        else:
            messages.add_message(request, messages.ERROR, "Your email sent didn't submit, make sure you write a valid email and try again.")
    form = NewsletterForm()
    return render(request, 'website/index.html' , context={'form': form})

# from django.shortcuts import redirect

# def redirect_view(request):
# #     response = redirect('/redirect-success/')
#     return render(request, 'mending.html')

templates/website/widgets/latest-posts.html
{% load blog_tags %}
{% load thumbnail %}
<div class="row">
    <div class="active-recent-blog-carusel">
        {% for post in latest_posts %}
        <div class="single-recent-blog-post item">
            <div class="thumb">
                <a href="{% url 'blog:single' pid=post.id %}">
                    {% thumbnail post.image "360x260" crop="center" as im %}
                    <img class="img-fluid" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="">
                    {% empty %}
                    <p>No image</p>
                    {% endthumbnail %}
                </a>
            </div>
            <div class="details">
                <div class="tags">
                    <ul>
                        {% for cat , count in categories %}
                        <li>
                            <a href="{% url 'blog:category' cat_name=cat %}">{{cat}}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <a href="{% url 'blog:single' pid=post.id %}">
                    <h4 class="title">{{post.title}}</h4>
                </a>
                <p>
                    {{post.summary}}
                </p>

                <h6 class="date">{{post.published_date|timesince|upto:', '}} ago</h6>
            </div>
        </div>
        {% endfor %}

    </div>
</div>