blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name  = 'blog'

urlpatterns = [

    path('' , blog_view, name='index'),
    path('<int:pid>', blog_single_view, name='single'),
    path('category/<str:cat_name>' , blog_view, name='category'),
    path('tag/<str:tag_name>' , blog_view, name='tag'),
    path('author/<str:author_username>' , blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('rss/feed/', LatestEntriesFeed()),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from website.views import *
from blog.sitemaps import *

sitemaps = {
    'static': StaticViewSitemap,
    'blog' : BlogSitemap,
}

# from website.views import redirect_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('', include('account.urls')),
    
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^robots\.txt', include('robots.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')), # The CKEditor path
    path('captcha/', include('captcha.urls')),
]

# admin interface Header
admin.site.site_header = 'Mikey'

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#MAINTENANCE_MODE
from django.urls import re_path
from django.conf import settings
from django.views.generic.base import TemplateView

if settings.MAINTENANCE_MODE:
   urlpatterns.insert(0, re_path(r'^', TemplateView.as_view(template_name='maintenance.html'), name='maintenance'))

website/urls.py
from django.urls import path
from website.views import *

app_name  = 'website'

urlpatterns = [

    path('' , index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view , name='contact'),
    path('newsletter', newsletter_view , name='newsletter'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField 
from django.core.exceptions import ValidationError
from blog.formatChecker import ContentTypeRestrictedFileField

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=60)
    class Meta:
        verbose_name_plural = 'Categories'
    def __str__(self):
        return self.name

class Post(models.Model):
    def validate_image(fieldfile_obj):
        filesize = fieldfile_obj.file.size
        megabyte_limit = 2.0
        if filesize > megabyte_limit*1024*1024:
            raise ValidationError("Max image size is %sMB" % str(megabyte_limit))
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg', validators=[validate_image])
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100)
    summary = models.TextField(blank=True)
    content = RichTextUploadingField() # CKEditor Rich Text Field
    audio = ContentTypeRestrictedFileField(upload_to='uploads/',
                                              content_types=[ 'audio/mpeg' ],
                                              max_upload_size=20971520,blank=True, null=True, verbose_name='audio') #'video/x-msvideo', 'application/pdf', 'video/mp4',
    video = ContentTypeRestrictedFileField(upload_to='uploads/',
                                              content_types=['video/mp4'],
                                              max_upload_size=20971520,blank=True, null=True, verbose_name='video')
    category = models.ManyToManyField(Category)
    tags = TaggableManager()
    counted_views = models.PositiveIntegerField(default=0)
    publish_status = models.BooleanField(default=False, )
    published_date = models.DateTimeField(null=True)
    login_require = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_date',)

    def __str__(self):
        return "{} - {}".format(self.title, self.id)
    
    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid':self.id})
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=70)
    email = models.EmailField()
    subject = models.CharField(max_length=200, null=True, blank=True, default=None)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ('-created_date',)
    def __str__(self):
        return self.name
    

blog/forms.py
from django.forms import ModelForm
from blog.models import *
from captcha.fields import CaptchaField

class CommentForm(ModelForm):
    captcha = CaptchaField()
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['subject'].required = False
        
    class Meta:
        model = Comment
        fields = ['post','name','email','subject','message']
        

blog/views.py
from django.shortcuts import render,get_object_or_404 , HttpResponseRedirect

from django.utils import timezone
from .models import *
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from blog.forms import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
# Create your views here.

def blog_view(request, **kwargs):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

    for post in posts: # turn publish_status on(Ture) if published_date is passed
        if post.publish_status == False:
            post.publish_status = True
            post.save() 

    if kwargs.get('cat_name') != None:  # posts by category
        posts = posts.filter(category__name=kwargs['cat_name'])

    if kwargs.get('author_username') != None:
        posts = posts.filter(author__username=kwargs['author_username'])
    
    if kwargs.get('tag_name') != None:
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])


    # pagination
    posts = Paginator(posts, 3)
    try :
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)



    context={'posts': posts}
    return render(request, 'blog/blog-home.html', context)


def blog_single_view(request,pid):
    post = get_object_or_404(Post, pk=pid , published_date__lte=timezone.now())
    post.counted_views +=1  # count views
    post.save()

    next_post = Post.objects.filter(publish_status=True,
                                     published_date__gt=post.published_date,
                                        ).order_by('published_date').first()
    previous_post = Post.objects.filter(publish_status=True,
                                         published_date__lt=post.published_date,
                                            ).order_by('published_date').last()
    
    # Comment Area
    comments = Comment.objects.filter(post=post.id,approved=True)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            # new_comment = form.save(commit=False)
            # new_comment.name = 'Unknown'     # warning simple-captcha is enabled.
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Your comment submited successfully.')
        else:
            messages.add_message(request, messages.ERROR, "Your comment didn't submit, make sure you have a comment ticket and try again.")

    if not post.login_require :
        form = CommentForm()
        context = { 'post': post,
                    'next_post': next_post,
                    'previous_post': previous_post,
                    'comments': comments,
                    'form': form,
                        }
        return render(request, 'blog/blog-single.html', context)
    else:
        if request.user.is_authenticated:
            form = CommentForm()
            context = { 'post': post,
                        'next_post': next_post,
                        'previous_post': previous_post,
                        'comments': comments,
                        'form': form,
                            }
            return render(request, 'blog/blog-single.html', context)
        else:
            return render(request, 'account/login.html', )
            


def blog_search(request):
    posts =Post.objects.filter(published_date__lte=timezone.now())
    if request.method == 'GET':
        if s := request.GET.get('s'):
            posts = posts.filter(summary__contains=s) | posts.filter(title__contains=s)
    context = {'posts':posts}
    return render(request, 'blog/blog-home.html', context)

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load thumbnail %}
{% load blog_tags %}
{% load humanize %}
<!-- start banner Area -->
<section class="banner-area relative blog-home-banner" id="home">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content blog-header-content col-lg-12">
				<h1 class="text-white">
					Dude You’re Getting
					better at Django!
				</h1>
				<p class="text-white">
					There is a moment in the life of any aspiring astronomer that it is time to buy that first
				</p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start top-category-widget Area -->
<section class="top-category-widget-area pt-90 pb-90 ">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget1.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Social life</h4>
								<span></span>
								<p>Enjoy your social life together</p>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget2.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Politics</h4>
								<span></span>
								<p>Be a part of politics</p>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget3.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Food</h4>
								<span></span>
								<p>Let the food be finished</p>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End top-category-widget Area -->

<!-- Start post-content Area -->
<section class="post-content-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				{% for post in posts %}
				<div class="single-post row">
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
							{% for cat in post.category.all %}
							{% if forloop.last %}
							<li><a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a></li>
							{% else %}
							<li><a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a></li>,
							{% endif %}

							{% endfor %}
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a
									href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a>
								<span class="lnr lnr-user"></span>
							</p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|date:"d M Y"}}

								</a> <span class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_views|intcomma}}
									Views</a> <span class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{% total_comments pid=post.id %} Comments</a> <span
									class="lnr lnr-bubble"></span></p>
						</div>
					</div>
					<div class="col-lg-9 col-md-9 ">
						<div class="feature-img">
							{% thumbnail post.image "540x304" crop="center" as im %}
							<img class="img-fluid" src="{{im.url}}" max-width="{{im.width}}" max-height="{{im.height}}"
								alt="">
							{% endthumbnail %}
						</div>
						<a class="posts-title" href="{% url 'blog:single' pid=post.id %}">
							<h3>{{post.title}}</h3>
						</a>
						<p class="excert">
							{{post.summary|safe}} </p>
						<a href="{% url 'blog:single' pid=post.id %}" class="primary-btn">View More</a>
					</div>
				</div>
				{% endfor %}

				{% if posts.has_other_pages %}
				<nav class="blog-pagination justify-content-center d-flex">
					<ul class="pagination">


						{% if posts.has_previous %}

						{% if posts.page != 1 %}
						<li class="page-item">
							<a href="?page=1" class="page-link" aria-label="First">
								<span aria-hidden="true">
									<span> First </span>
								</span>
							</a>
						</li>
						{% if posts.page != 2 %}
						<li class="page-item">
							<a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
								<span aria-hidden="true">
									<span class="lnr lnr-chevron-left"></span>
								</span>
							</a>
						</li>
						{% endif %}

						{% endif %}
						<li class="page-item"><a href="?page={{posts.previous_page_number}}"
								class="page-link">{{posts.previous_page_number}}</a></li>

						{% endif %}

						<li class="page-item active"><a href="#" class="page-link">{{posts.number}}</a></li>
						{% if posts.has_next %}
						<li class="page-item"><a href="?page={{posts.next_page_number}}"
								class="page-link">{{posts.next_page_number}}</a></li>
						<li class="page-item">
							<a href="?page={{posts.next_page_number}}" class="page-link" aria-label="Next">
								<span aria-hidden="true">
									<span class="lnr lnr-chevron-right"></span>
								</span>
							</a>
						</li>
						<li class="page-item">
							<a href="?page={{posts.paginator.num_pages}}" class="page-link" aria-label="Last">
								<span aria-hidden="true">
									<span> Last </span>
								</span>
							</a>
						</li>
						{% endif %}
					</ul>
				</nav>
				{% endif %}
			</div>
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					{% include 'blog/right-side/blog-search.html' %}
					{% include 'blog/right-side/blog-writer.html' %}

					<!--{% include 'blog/right-side/blog-tag-cloud.html' %}-->
					
					{% latest_posts %}
					{% include 'blog/right-side/blog-ads.html' %}
					{% category %}
					{% include 'blog/right-side/blog-newsletter.html' %}
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End post-content Area -->
{% endblock %}

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load thumbnail %}
{% load blog_tags %}
{% load humanize %}
<!-- start banner Area -->
<section class="relative about-banner">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					{{post.title}}
				</h1>
				<p class="text-white link-nav"><a href="{% url 'website:index' %}">Home </a> <span
						class="lnr lnr-arrow-right"></span><a href="{% url 'blog:index' %}">Blog </a> <span
						class="lnr lnr-arrow-right"></span> <a href="#">{{post.title}}</a></p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start post-content Area -->
<section class="post-content-area single-post-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				<div class="single-post row">
					<div class="col-lg-12">
						<div class="feature-img">
							<img class="img-fluid" src="{{post.image.url}}" alt="">
						</div>
					</div>
					<div class="col-lg-12 meta-details">

						<div class="user-details row" style="margin:auto; align-content: center;">

							<p class="user-name col-sm-auto "
								style="margin:auto; text-align: center; align-self:center;"><a
									href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a>
								<span class="lnr lnr-user"></span>
							</p>
							<p class="date col-sm-auto " style="margin:auto; text-align: center; align-self:center;"><a
									href="#">{{post.published_date|date:"d M Y"}}</a> <span
									class="lnr lnr-calendar-full"></span></p>
							<p class="view col-sm-auto " style="margin:auto; text-align: center; align-self:center;"><a
									href="#">{{post.counted_views|intcomma}} Views</a> <span class="lnr lnr-eye"></span>
							</p>
							<p class="comments col-sm-auto "
								style="margin:auto; text-align: center; align-self:center;"><a
									href="#">{{comments|length}} Comments</a>
								<span class="lnr lnr-bubble"></span>
							</p>
							<ul class="social-links col-sm-12 "
								style="margin: auto; margin-top: 1.5%; text-align:left;">
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="https://github.com/mjz589/"><i class="fa fa-github"></i></a></li>
								<li><a href="https://t.me/www_Mohammad"><i class="fa fa-telegram"></i></a></li>
								<li><a href="https://www.instagram.com/mmd.javad__/"><i class="fa fa-instagram"></i></a>
								</li>
							</ul>
						</div>

					</div>
					<div class="col-lg-12 col-md-9">
						<h3 class="mt-20 mb-20">{{post.title}}</h3>
						<p class="excert">
							{{post.summary|safe}}
						</p>
						<p class="excert">
							{{post.content|safe}}
						</p>
						<p class="excert">
							{% if post.video %}
							<video width="320" height="240" controls>
								<source src="{{post.video.url}}" type="video/mp4">
							</video>
							{% endif %}
						</p>
						<p>{% if post.audio %}
							<audio controls>
								<source src="{{post.audio.url}}" type="audio/mpeg">
							</audio>
							{% endif %}
						</p>

						</p>
					</div>
					<div class="col-lg-12 meta-details">

						<ul class="tags col-xs-3" style="text-align:right;">
							{% for cat in post.category.all %}
							{% if forloop.last %}
							<li><a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a></li>
							{% else %}
							<li><a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}},</a></li>
							{% endif %}
							{% endfor %}
						</ul>
					</div>
					<div class="col-lg-12">
						<div class="quotes">
							"If you stare into the abyss, the abyss stares back at you."
						</div>
						<div class="row mt-30 mb-30">
							<div class="col-6">
								<img class="img-fluid" src="{% static 'img/blog/post-img1.jpg' %}" alt="">
							</div>
							<div class="col-6">
								<img class="img-fluid" src="{% static 'img/blog/post-img2.jpg' %}" alt="">
							</div>
						</div>
					</div>
				</div>
				<div class="navigation-area">
					<div class="row">
						{% if previous_post %}
						<div
							class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
							<div class="thumb">
								{% thumbnail previous_post.image "90x60" crop="center" as im %}
								<a href="{% url 'blog:single' previous_post.id %}"><img class="img-fluid"
										src="{{im.url}}" width="{{ im.width }}" height="{{ im.height }}" alt=""></a>
								{% endthumbnail %}
							</div>
							<div class="arrow">
								<a href="{% url 'blog:single' previous_post.id %}"><span
										class="lnr text-white lnr-arrow-left"></span></a>
							</div>

							<div class="detials">
								<p>Prev Post</p>
								<a href="{% url 'blog:single' previous_post.id %}">
									<h4>{{previous_post.title}} </h4>
								</a>
							</div>
						</div>
						{% endif %}
						{% if next_post %}
						<div
							class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
							<div class="detials">
								<p>Next Post</p>
								<a href="{% url 'blog:single' next_post.id %}">
									<h4>{{next_post.title}}</h4>
								</a>
							</div>
							<div class="arrow">
								<a href="{% url 'blog:single' next_post.id %}"><span
										class="lnr text-white lnr-arrow-right"></span></a>
							</div>
							<div class="thumb">
								{% thumbnail next_post.image "90x60" crop="center" as im %}
								<a href="{% url 'blog:single' next_post.id %}"><img class="img-fluid" src="{{im.url}}"
										width="{{ im.width }}" height="{{ im.height }}" alt=""></a>
								{% endthumbnail %}
							</div>
						</div>
						{% endif %}
					</div>
				</div>
				
				<div class="comments-area">
					<h4>{{comments|length}} Comments</h4>
					<div class="comment-list">
						{% for comment in comments %}

						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c1.png' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">{{comment.name}}</a></h5>
									<p class="date">{{comment.created_date|naturaltime}}</p>
									<p class="comment">
										{{comment.message}}
									</p>
								</div>
							</div>

							<!--
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div> -->

						</div>
						{% empty %}
						<p style="text-align:center">No commnets yet. Be the first one to tell about your thoughts to
							us!</p>
						{% endfor %}
					</div>
					<!--
					<div class="comment-list left-padding">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c2.jpg' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">Elsie Cunningham</a></h5>
									<p class="date">December 4, 2017 at 3:12 pm </p>
									<p class="comment">
										Never say goodbye till the end comes!
									</p>
								</div>
							</div>
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
						</div>
					</div> -->
				</div>

				<div class="comment-form">
					<h4>Leave a Comment</h4>
					<form method="post" action="{% url 'blog:single' pid=post.id %}">
						{% csrf_token %}
						<input type="hidden" name="post" value="{{post.id}}">
						{% if request.user.is_authenticated %}
						<input type="hidden" name="name" value="{{request.user.username}}">
						<h4>as {{request.user.get_full_name}}:</h4>
						<input type="hidden" name="email" value="{{request.user.email}}">

						{% else %}
						<div class="form-group form-inline">
							<div class="form-group col-lg-6 col-md-12 name">
								<input type="text" class="form-control" name="name" placeholder="Enter Name"
									onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
							</div>
							<div class="form-group col-lg-6 col-md-12 email">
								<input type="email" class="form-control" name="email" placeholder="Enter email address"
									onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
							</div>
						</div>
						{% endif %}
						<div class="form-group">
							<input type="text" class="form-control" name="subject" placeholder="Subject"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
						</div>
						<div class="form-group">
							<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'"
								required=""></textarea>

						</div>
						<div class="pb-3 pt-3">{{form.captcha}}</div>
						<button type="submit" class="primary-btn text-uppercase">Post Comment</button>
					</form>
					{% include 'messages.html' %}
				</div>

			</div>
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					{% include 'blog/right-side/blog-search.html' %}
					{% include 'blog/right-side/blog-writer.html' %}
					{% latest_posts %}
					{% include 'blog/right-side/blog-ads.html' %}
					{% category %}
					{% include 'blog/right-side/blog-newsletter.html' %}
					{% include 'blog/right-side/blog-tag-cloud.html' %}
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End post-content Area -->
{% endblock %}