blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name  = 'blog'

urlpatterns = [

    path('' , blog_view, name='index'),
    path('<int:pid>', blog_single_view, name='single'),
    path('category/<str:cat_name>' , blog_view, name='category'),
    path('tag/<str:tag_name>' , blog_view, name='tag'),
    path('author/<str:author_username>' , blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('rss/feed/', LatestEntriesFeed()),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from website.views import *
from blog.sitemaps import *

sitemaps = {
    'static': StaticViewSitemap,
    'blog' : BlogSitemap,
}

# from website.views import redirect_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('', include('account.urls')),
    
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^robots\.txt', include('robots.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')), # The CKEditor path
    path('captcha/', include('captcha.urls')),
]

# admin interface Header
admin.site.site_header = 'Mikey'

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#MAINTENANCE_MODE
from django.urls import re_path
from django.conf import settings
from django.views.generic.base import TemplateView

if settings.MAINTENANCE_MODE:
   urlpatterns.insert(0, re_path(r'^', TemplateView.as_view(template_name='maintenance.html'), name='maintenance'))

website/urls.py
from django.urls import path
from website.views import *

app_name  = 'website'

urlpatterns = [

    path('' , index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view , name='contact'),
    path('newsletter', newsletter_view , name='newsletter'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField 
from django.core.exceptions import ValidationError
from blog.formatChecker import ContentTypeRestrictedFileField

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=60)
    class Meta:
        verbose_name_plural = 'Categories'
    def __str__(self):
        return self.name

class Post(models.Model):
    def validate_image(fieldfile_obj):
        filesize = fieldfile_obj.file.size
        megabyte_limit = 2.0
        if filesize > megabyte_limit*1024*1024:
            raise ValidationError("Max image size is %sMB" % str(megabyte_limit))
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg', validators=[validate_image])
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100)
    summary = models.TextField(blank=True)
    content = RichTextUploadingField() # CKEditor Rich Text Field
    audio = ContentTypeRestrictedFileField(upload_to='uploads/',
                                              content_types=[ 'audio/mpeg' ],
                                              max_upload_size=20971520,blank=True, null=True, verbose_name='audio') #'video/x-msvideo', 'application/pdf', 'video/mp4',
    video = ContentTypeRestrictedFileField(upload_to='uploads/',
                                              content_types=['video/mp4'],
                                              max_upload_size=20971520,blank=True, null=True, verbose_name='video')
    category = models.ManyToManyField(Category)
    tags = TaggableManager()
    counted_views = models.PositiveIntegerField(default=0)
    publish_status = models.BooleanField(default=False, )
    published_date = models.DateTimeField(null=True)
    login_require = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_date',)

    def __str__(self):
        return "{} - {}".format(self.title, self.id)
    
    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid':self.id})
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=70)
    email = models.EmailField()
    subject = models.CharField(max_length=200, null=True, blank=True, default=None)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ('-created_date',)
    def __str__(self):
        return self.name
    

blog/forms.py
from django.forms import ModelForm
from blog.models import *
from captcha.fields import CaptchaField

class CommentForm(ModelForm):
    captcha = CaptchaField()
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['subject'].required = False
        
    class Meta:
        model = Comment
        fields = ['post','name','email','subject','message']
        

blog/views.py
from django.shortcuts import render,get_object_or_404 , HttpResponseRedirect

from django.utils import timezone
from .models import *
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from blog.forms import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
# Create your views here.

def blog_view(request, **kwargs):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

    for post in posts: # turn publish_status on(Ture) if published_date is passed
        if post.publish_status == False:
            post.publish_status = True
            post.save() 

    if kwargs.get('cat_name') != None:  # posts by category
        posts = posts.filter(category__name=kwargs['cat_name'])

    if kwargs.get('author_username') != None:
        posts = posts.filter(author__username=kwargs['author_username'])
    
    if kwargs.get('tag_name') != None:
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])


    # pagination
    posts = Paginator(posts, 3)
    try :
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)



    context={'posts': posts}
    return render(request, 'blog/blog-home.html', context)


def blog_single_view(request,pid):
    post = get_object_or_404(Post, pk=pid , published_date__lte=timezone.now())
    post.counted_views +=1  # count views
    post.save()

    next_post = Post.objects.filter(publish_status=True,
                                     published_date__gt=post.published_date,
                                        ).order_by('published_date').first()
    previous_post = Post.objects.filter(publish_status=True,
                                         published_date__lt=post.published_date,
                                            ).order_by('published_date').last()
    
    # Comment Area
    comments = Comment.objects.filter(post=post.id,approved=True)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            # new_comment = form.save(commit=False)
            # new_comment.name = 'Unknown'     # warning simple-captcha is enabled.
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Your comment submited successfully.')
        else:
            messages.add_message(request, messages.ERROR, "Your comment didn't submit, make sure you have a comment ticket and try again.")

    if not post.login_require :
        form = CommentForm()
        context = { 'post': post,
                    'next_post': next_post,
                    'previous_post': previous_post,
                    'comments': comments,
                    'form': form,
                        }
        return render(request, 'blog/blog-single.html', context)
    else:
        if request.user.is_authenticated:
            form = CommentForm()
            context = { 'post': post,
                        'next_post': next_post,
                        'previous_post': previous_post,
                        'comments': comments,
                        'form': form,
                            }
            return render(request, 'blog/blog-single.html', context)
        else:
            return render(request, 'account/login.html', )
            


def blog_search(request):
    posts =Post.objects.filter(published_date__lte=timezone.now())
    if request.method == 'GET':
        if s := request.GET.get('s'):
            posts = posts.filter(summary__contains=s) | posts.filter(title__contains=s)
    context = {'posts':posts}
    return render(request, 'blog/blog-home.html', context)

templates/blog/right-side/blog-ads.html
{% load static %}
<div class="single-sidebar-widget ads-widget">
    <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
</div>

templates/blog/right-side/blog-category.html
{% load static %}
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
        {% for name,count in categories.items %}
        <li>
            <a href="{% url 'blog:category' cat_name=name %}" class="d-flex justify-content-between">
                <p>{{name}}</p>
                <p>{{count}}</p>
            </a>
        </li>
        {% endfor %}															
    </ul>
</div>	

templates/blog/right-side/blog-latest-posts.html
{% load blog_tags %}
{% load thumbnail %}

<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Latest Posts</h4>
    <div class="popular-post-list">
        {% for post in pop_posts %}
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                {% thumbnail post.image "100x60" crop="center" as im %}
                <img class="img-fluid" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="">
                {% empty %}
                <p>No image</p>
                {% endthumbnail %}
            </div>
            <div class="details">
                <a href="{% url 'blog:single' pid=post.id %}">
                    <h6>{{post.title}}</h6>
                </a>
                <p>{{post.published_date|timesince|upto:', '}} ago</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

templates/blog/right-side/blog-newsletter.html
<div class="single-sidebar-widget newsletter-widget">
    <h4 class="newsletter-title">Newsletter</h4>
    <p>
        Here, I focus on a range of items and features that we use in life without
        giving them a second thought.
    </p>
    <div class="form-group d-flex flex-row">
        <div class="col-autos">
            <form class="form-area text-right" action="{% url 'website:newsletter' %}" method="post">
                {% csrf_token %}
                <div class="input-group d-flex flex-row">

                    
                    <input name="email" placeholder="Enter email"
                        pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$" onfocus="this.placeholder = ''"
                        onblur="this.placeholder = 'Enter email'" class="common-input mb-20 form-control"
                        required="" type="email">

                    <button href="#" type="submit" class="bbtns">Subcribe</button>

                </div>
            </form>
        </div>
    </div>
    <p class="text-bottom">
        You can unsubscribe at any time
    </p>
</div>

templates/blog/right-side/blog-popular-posts.html
{% load static %}
{% load blog_tags %}
{% load thumbnail %}

<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Popular Posts</h4>
    <div class="popular-post-list">
        {% for post in pop_posts %}
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                {% thumbnail post.image "100x60" crop="center" as im %}
                <img class="img-fluid" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="">
                {% empty %}
                <p>No image</p>
                {% endthumbnail %}
            </div>
            <div class="details">
                <a href="{% url 'blog:single' post.id %}">
                    <h6>{{post.title}}</h6>
                </a>
                <p>{{post.published_date|timesince|upto:', '}} ago</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

templates/blog/right-side/blog-search.html
<div class="single-sidebar-widget search-widget">
    <form method="get" class="search-form" action="{% url 'blog:search' %}">
        <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''"
            onblur="this.placeholder = 'Search Posts'">
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

templates/blog/right-side/blog-tag-cloud.html
<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Tag Clouds</h4>
    <ul>
        {% for tag in post.tags.all %}
        <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></li>
        {% endfor %}
    </ul>
</div>

templates/blog/right-side/blog-writer.html
{% load static %}
<div class="single-sidebar-widget user-info-widget">
    <img src="{% static 'img/blog/user-info.png' %}" alt="">
    <a href="#">
        <h4>Mohamad Javad Zare</h4>
    </a>
    <p>
        Back-End Developer and Blog Writer
    </p>
    <ul class="social-links">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="https://github.com/mohamadjavadzare"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-behance"></i></a></li>
    </ul>
    <p>
        Boot camps have its supporters andit sdetractors. Some people do not understand why you
        should have to spend money on boot camp when you can get. Boot camps have itssuppor ters
        andits detractors.
    </p>
</div>